FROM mineru:latest
COPY ./web_demo /opt/webdemo

WORKDIR /opt/webdemo
RUN /bin/bash -c "source /opt/mineru_venv/bin/activate && pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple"

# 创建必要的目录
RUN mkdir -p /root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer \
    && mkdir -p /root/.paddleocr/whl/rec/ch/ch_PP-OCRv4_rec_infer \
    && mkdir -p /root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer \
&& wget -O /root/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer/ch_PP-OCRv4_det_infer.tar https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar \
    && wget -O /root/.paddleocr/whl/rec/ch/ch_PP-OCRv4_rec_infer/ch_PP-OCRv4_rec_infer.tar https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_rec_infer.tar \
    && wget -O /root/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer/ch_ppocr_mobile_v2.0_cls_infer.tar https://paddleocr.bj.bcebos.com/dygraph_v2.0/ch/ch_ppocr_mobile_v2.0_cls_infer.tar


EXPOSE 5559

# 保持虚拟环境激活状态执行应用
CMD ["/opt/mineru_venv/bin/python", "app.py"]
